<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
?>

<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<h3><?php echo $translate('Item'); ?></h3>
<?php $this->trigger('view.show.before'); ?>
<?php if ($embedMedia && $itemMedia): ?>
    <div class="media-embeds">
    <?php foreach ($itemMedia as $media):
        echo $media->render();
    endforeach;
    ?>
    </div>
<?php endif; ?>


<div class="item-show">
<!-- display image and infos -->
<?php if (!$embedMedia && $itemMedia): ?>
<div class="item-media">
<?php
    $itemMediaImg = "<img class='item-img' src=".$itemMedia[0]->originalUrl()." width=300px>";
	echo $itemMediaImg;

    

	//experiments from docs: https://omeka.org/s/docs/developer/key_concepts/representations/
	#echo "id: ".$item->id()."<br/>";
	#echo "title: ".$item->displayTitle()."<br/>";
	#echo "desc: ".$item->displayDescription()."<br/>";
?>
    <!-- <div class="item-overlay">View item</div> -->
</div>
<?php endif; ?>


<!-- display item metadata -->
<div class="item-metadata">
  <?php echo $item->displayValues(); ?>
  <div class="property">
     <?php $itemSets = $item->itemSets(); ?>
     <?php if (count($itemSets) > 0): ?>
     <h4><?php echo $translate('Item sets'); ?></h4>
     <?php foreach ($itemSets as $itemSet): ?>
     <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
     <?php endforeach; ?>
     <?php endif; ?>
  </div>
  <br/><br/>
</div>

</div>

<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3><?php echo $translate('Linked resources'); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>

<div id="mirador-1" class="mirador viewer"></div>
<div class="delimiter-block"></div>
<?php $this->trigger('view.show.after'); ?>

<script>init_mirador_item_link();</script>
