<?php
$this->htmlElement('body')->appendAttribute('class', 'page');
$this->pageTitle($page->title(), 2);
$showPagePagination = $this->siteSetting('show_page_pagination', true);
?>

<?php
$nav = $site->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);


$path =  $_SERVER["REQUEST_URI"];
$parts = explode('/', $path);
$re = '/page\/view(.*)/';
$item = "";
$is_view = false;
preg_match($re, $path, $matches, PREG_OFFSET_CAPTURE, 0);
if ($matches):
  $is_view = true;
  $groups = array_values($matches);
  $item = $matches[1][0];
endif;
?>

<?php if ($activePage): ?>
    <?php if ($activePage['depth'] !== 0): ?>
    <nav class="breadcrumbs"><?php echo $nav->breadcrumbs(); ?></nav>
    <?php endif; ?>
<?php endif; ?>

<?php if ($activePage): ?>
    <?php if ($this->displayNavigation && $activePage['page']->hasPages()): ?>
    <nav class="sub-menu"><?php echo $nav->menu()->renderSubMenu(); ?></nav>
    <?php endif; ?>
<?php endif; ?>


<?php
  //echo "active page: ".$activePage['page'];
  if ($activePage['page'] == "Home"):

    $itemNum = $this->api()->search('items', ['limit' => 0])->getTotalResults();
    $item_setsNum = $this->api()->search('item_sets', ['limit' => 0])->getTotalResults();
    //$itemNum = "5";

    echo '<div id="main_jumbotron" class="jumbotron">
	<div id="search_container">
	  <div id="search_pre">
	   <span class="fixed-txt">Cerca nella Digital Library fra </span>
	   <span class="var-txt">'.$itemNum.'</span><span class="fixed-txt"> risorse e
       <span class="var-txt">'.$item_setsNum.'</span> collezioni:</span>
	</div>
    <div id="jumbotron_search">';
    echo $this->partial('common/search-form');
    echo '</div></div></div>';

  endif;
?>

<?php $this->trigger('view.show.before'); ?>
<div class="blocks">
    <?php echo $this->content; ?>
    <div class="site-page-pagination">
        <a class="btn btn-primary" href="javascript:history.back();" aria-label="previous page">
        <i class="fa fa-arrow-left" aria-hiddenb="true"></i> Indietro</a>
        </div>
</div>
<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
<?php echo $this->sitePagePagination(); ?>
<?php endif; ?>

<?php if ($is_view === true): ?>
  <script>init_view();</script>
<?php endif; ?>


