<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet($this->assetUrl('css/dharc.css'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');

#dharc main js
$this->headScript()->prependFile($this->assetUrl('js/dharc_main.js'));

$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));

$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
$userBar = $this->userBar();
$logo = $this->themeSettingAssetUrl('logo');
if ($logo):
    $title = '<img src="' . $this->escapeHtml($logo) . '">';
endif;
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <?php echo $userBar; ?>
        <header>
            <?php if ($this->themeSetting('logo')): ?>
            <a href="<?php echo $site->url(); ?>" class="site-title"><img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" title="Logo"></a>
            <?php else: ?>
            <a href="<?php echo $site->url(); ?>" class="site-title"><?php echo $this->pageTitle($site->title()); ?></a>
            <?php endif; ?>
            <nav>
            <?php
            echo $site->publicNav()->menu()->renderMenu(null, [
                'maxDepth' => $this->themeSetting('nav_depth') - 1
            ]);
            ?>
            </nav>

            <div id="search">
              <?php echo $this->partial('common/search-form'); ?>
            </div>

        </header>
        <!-- search container disable here
        <div id="main_jumbotron" class="jumbotron">
          <div id="search_container">
              <div id="search_pre"><span class="fixed-txt">Search within our Digital Library of over </span><span class="var-txt">1000</span><span class="fixed-txt"> items:</span></div>
              <div id="search">

              </div>
          </div>
        </div>
        -->
        <div id="content" role="main">
            <?php echo $this->content; ?>
        </div>
        <footer>
            <div class="top-footer">
                <div class="first-section">
                  <!--<p class="footer-text"><a class="footer-a cursor-pointer" onclick="changePage('documentazione_progetto')">Documentazione del progetto</a></p>-->
                  <p class="title">DL FICLIT</p>
                  <p class="footer-text"><a href="https://www.unibo.it/en/university/privacy-policy-and-legal-notes/privacy-policy/information-note-on-the-processing-of-personal-data" alt="Privacy policy" target="_black" class="footer-a">Privacy Policy</a></p>
                  <p class="footer-text"><a href="https://www.unibo.it/en/university/privacy-policy-and-legal-notes/legal-notes" alt="Legal notes" target="_black" class="footer-a">Legal notes</a></p>
                </div>

                <div class="second-section">
                  <p class="title">/DH.arc - Digital Humanities Advanced Research Centre</p>
                  <span class="footer-text"><a href="https://centri.unibo.it/dharc/en" target="_black" alt="Dharc website" class="link_footer footer-a">About</a></span>
                  <span class="footer-text"><a href="https://centri.unibo.it/dharc/en/research/projects-at-dh-arc" target="_black" alt="Dharc website" class="link_footer footer-a">Projects</a></span>
                  <span class="footer-text"><a href="https://centri.unibo.it/dharc/en/contacts" target="_black" alt="Dharc website" class="link_footer footer-a">Contacts</a></span>
                </div>
            </div>

            <div class="bottom-footer">
              <div class="first-section">
                <p class="footer-text">© Copyright (c) 2020 by /DH.arc - Digital Humanities Advanced Research Centre + Department of Computer Science, University of Bologna.</p>
              </div>
            </div>

        </footer>
    </body>
</html>
